// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4ffIbr12OJboIjciD4ni9HNmGecE5no',
    appId: '1:13526936105:web:78f56fb0a9b647e29e0a38',
    messagingSenderId: '13526936105',
    projectId: 'todo-d101a',
    authDomain: 'todo-d101a.firebaseapp.com',
    storageBucket: 'todo-d101a.appspot.com',
    measurementId: 'G-281JHCH9SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5eHrT0_7wdX21vVEbOXW0D9C2ZaQRB7w',
    appId: '1:13526936105:android:3b8c328c7809d87b9e0a38',
    messagingSenderId: '13526936105',
    projectId: 'todo-d101a',
    storageBucket: 'todo-d101a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAof3qFdeJlH3p232DpZW90Z2fcxiPl3Bs',
    appId: '1:13526936105:ios:eb964e193007edfa9e0a38',
    messagingSenderId: '13526936105',
    projectId: 'todo-d101a',
    storageBucket: 'todo-d101a.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAof3qFdeJlH3p232DpZW90Z2fcxiPl3Bs',
    appId: '1:13526936105:ios:95072876d1c5e94a9e0a38',
    messagingSenderId: '13526936105',
    projectId: 'todo-d101a',
    storageBucket: 'todo-d101a.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
